---
linear_velocity:
  value: 250.0
  description: линейная скорость окраски, мм/с, g01
idling_velocity:
  value: 400.0
  description: линейная скорость холостого хода, мм/с, g00
linear_acceleration:
  value: 450.0
  description: линейной ускорение мм/c2
max_angular_velocity:
  value: 101.0
  description: максимальная угловая скорость моторов, •/сек
max_angular_acceleration:
  value: 200.0
  description: максимальное угловое ускорение моторов, •/сек2
max_segment_length:
  value: 30.0
  description: точность апроксимации, мм
motor_pulley_diameter:
  value: 128.92
  description: диаметр шкива
initial_x:
  value: 3500.0
  description: начальная длина левого ремня, мм
initial_y:
  value: 3500.0
  description: начальная длина правого ремня, мм
start_from:
  value: 0.0
  description: с какой траектории начать рисование
crop_x:
  value: 0.0
  description: левый верхний угол для обрезки
crop_y:
  value: 0.0
  description: левый верхний угол для обрезки
crop_w:
  value: 0.0
  description: ширина прямоугольника обрезки
crop_h:
  value: 0.0
  description: высота прямоугольника обрезки
move_x:
  value: 0.0
  description: смещение рисунка, если надо
move_y:
  value: 0.0
  description: смещение рисунка, если надо
max_spray_length:
  value: 87000.0
  description: длина окраски одним баллончиком краски, мм
  hidden: true
canvas_size_x:
  value: 6000.0
  description: ширина холста (между креплениями моторов)
canvas_size_y:
  value: 1500.0
  description: высота холста
dm:
  value: 200.0
  description: расстояние между моторами
dy:
  value: 100.0
  description: насколько сопло ниже линии моторов
simulation_velocity:
  value: 1500.1
  description: скорость симуляции, mm/sec
image_name:
  value: test.svg
  description: имя файла
version:
  value: 1.0
  description: версия данных в кэше
  hidden: true
correction_left:
  value: 200.0
  description: корректировка левого ремня
correction_right:
  value: 250.0
  description: корректировка правого ремня
