linear_velocity : 20000.0 # линейная скорость окраски, мм/мин, g01
ff_velocity : 24000.0 # линейная скорость холостого хода, мм/мин, g00
max_segment_length : 10.0 # точность апроксимации, мм
initial_x : 15000.0 # начальная длина левого ремня, мм
initial_y : 15000.0 # начальная длина правого ремня, мм
#
#crop_x : 0 # левый верхний угол для обрезки
#crop_y : 0 # левый верхний угол для обрезки
#crop_w : 0 # ширина прямоугольника обрезки
#crop_h : 2450 # высота прямоугольника обрезки
##
#move_x : 148 # смещение рисунка, если надо
#move_y : 100 # смещение рисунка, если надо
#
max_spray_length : 87000.0 # длина окраски одним баллончиком краски, мм
#
canvas_size_x : 10600 # ширина холста
canvas_size_y : 36000.0 # высота холста
dm: 350.0 #расстояние между моторами
dy: 50.0 #насколько сопло ниже линии моторов