---
linear_velocity:
  value: 100.0
  description: линейная скорость окраски, мм/с, g01
idling_velocity:
  value: 200.0
  description: линейная скорость холостого хода, мм/с, g00
linear_acceleration:
  value: 50.0
  description: линейной ускорение мм/c2
max_angular_velocity:
  value: 180.0
  description: максимальная угловая скорость моторов, •/сек
max_angular_acceleration:
  value: 250.0
  description: максимальное угловое ускорение моторов, •/сек2
max_segment_length:
  value: 50.0
  description: точность апроксимации, мм
motor_pulley_diameter:
  value: 200.0
  description: диаметр шкива
initial_x:
  value: 500.0
  description: начальная длина левого ремня, мм
initial_y:
  value: 500.0
  description: начальная длина правого ремня, мм
crop_x:
  value: 0
  description: левый верхний угол для обрезки
crop_y:
  value: 0
  description: левый верхний угол для обрезки
crop_w:
  value: 0
  description: ширина прямоугольника обрезки
crop_h:
  value: 2450
  description: высота прямоугольника обрезки
move_x:
  value: 148
  description: смещение рисунка, если надо
move_y:
  value: 100
  description: смещение рисунка, если надо
max_spray_length:
  value: 87000.0
  description: длина окраски одним баллончиком краски, мм
canvas_size_x:
  value: 800.0
  description: ширина холста
canvas_size_y:
  value: 1000.0
  description: высота холста
dm:
  value: 100.0
  description: расстояние между моторами
dy:
  value: 50.0
  description: насколько сопло ниже линии моторов
simulation_velocity:
  value: 500.0
  description: скорость симуляции, mm/sec
