linear_velocity : 200.0 # линейная скорость окраски, мм/с, g01
idling_velocity : 400.0 # линейная скорость холостого хода, мм/с, g00
linear_acceleration : 400.0 # линейной ускорение мм/c2
max_angular_velocity : 180.0 # максимальная угловая скорость моторов, •/сек
max_angular_acceleration : 250.0 # максимальное угловое ускорение моторов, •/сек2
max_segment_length : 30.0 # точность апроксимации, мм
motor_pulley_diameter : 200.0 #диаметр шкива
initial_x : 15000.0 # начальная длина левого ремня, мм
initial_y : 15000.0 # начальная длина правого ремня, мм
#
#crop_x : 0 # левый верхний угол для обрезки
#crop_y : 0 # левый верхний угол для обрезки
#crop_w : 0 # ширина прямоугольника обрезки
#crop_h : 2450 # высота прямоугольника обрезки
##
#move_x : 148 # смещение рисунка, если надо
#move_y : 100 # смещение рисунка, если надо
#
#max_spray_length : 87000.0 # длина окраски одним баллончиком краски, мм
#
canvas_size_x : 10600 # ширина холста
canvas_size_y : 36000.0 # высота холста
dm: 350.0 #расстояние между моторами
dy: 50.0 #насколько сопло ниже линии моторов